
stages:          # List of stages for jobs, and their order of execution
  - deploy



deploy:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  trigger:
        project: ckan-mtes/gd-bastion
        branch: master
        strategy: depend

