
stages:          # List of stages for jobs, and their order of execution
  - deploy



deploy:      
  stage: deploy 
  variables:
    CKAN_EXT : "ckanext-dsfr" 
  trigger:
        project: ckan-mtes/gd-bastion
        branch: develop
        strategy: depend

